name: Semantic Release Pipeline

on:
  push:
    branches: [main]

jobs:
  semantic_release:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '10.0.x' ]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0

      - name: Setup dotnet
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 #v5.2 
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
      