@unified_customer_profile.api_HostAddress = http://localhost:3000

GET {{unified_customer_profile.api_HostAddress}}/customer/{id}
GET {{unified_customer_profile.api_HostAddress}}/status
Accept: application/json

###
